### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by hexagonius** [devlooped/moq#1487]
## Describe the Bug

The in-depth documentation link does not work https://moq.github.io/moq/

**Comment by vicheanath** [comment]
it `https://moq.github.io/` is correct ?

**Comment by ashanan** [comment]
@vicheanath I wonder if linking to the wiki might be better? https://github.com/moq/moq4/wiki

While the URL you shared works, the most recent post there is from 2013 and the work in progress documentation site linked from there has a bad SSL certificate so I haven't clicked through to see if it's actually up or not.

**Comment by vicheanath** [comment]
that grate I think so, I will create PR to update it.

**Comment by ashanan** [comment]
Working on one already :)

**Comment by ashanan** [comment]
@vicheanath I'll close mine, we don't need two of these :)

**Comment by vicheanath** [comment]
I'm here to close my PR, my misunderstanding. so keep it there.

**Comment by kzu** [comment]
fixed in main repo readme, pointing to https://github.com/devlooped/moq/wiki/Quickstart

**Comment by hexagonius** [comment]
The link in question is still broken.

The In-depth one

![Screenshot_20240724-070323~2](https://github.com/user-attachments/assets/69c36582-4005-42bd-b6f5-b29ac037dbf3)

**Comment by kzu** [comment]
Gone!
